// <auto-generated />
using System;
using Exo_EFC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exo_EFC.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230606124007_Use_NewSequentialId")]
    partial class Use_NewSequentialId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Exo_EFC.DAL.Entities.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Movie_Id")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MainActor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MovieId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("MovieId"));

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Movie", (string)null);

                    b.HasCheckConstraint("CK_Movie__ReleaseYear", "ReleaseYear > 1975");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("31c869b5-da2a-48ff-ae67-f5ffd5fc46c8"),
                            Director = "Georges Lucas",
                            Genre = "Science-Fiction",
                            MainActor = "Mark Hammil",
                            ReleaseYear = (short)1977,
                            Title = "Star Wars : Un nouvel espoir"
                        },
                        new
                        {
                            MovieId = new Guid("38643a14-6a29-454c-99bf-316847afdd7f"),
                            Director = "Georges Lucas",
                            Genre = "Science-Fiction",
                            MainActor = "Mark Hammil",
                            ReleaseYear = (short)1980,
                            Title = "Star Wars : L'empire contre-attaque"
                        },
                        new
                        {
                            MovieId = new Guid("cd0a8e26-218b-4d3d-a686-fe4626831296"),
                            Director = "Georges Lucas",
                            Genre = "Science-Fiction",
                            MainActor = "Mark Hammil",
                            ReleaseYear = (short)1983,
                            Title = "Star Wars : Le retour du Jedi"
                        },
                        new
                        {
                            MovieId = new Guid("ff75ea0e-f7e6-43ca-9dd3-56efdd236088"),
                            Director = "Lexi Alexander",
                            Genre = "Société",
                            MainActor = "Charlie Hunnam",
                            ReleaseYear = (short)2005,
                            Title = "Hooligans"
                        },
                        new
                        {
                            MovieId = new Guid("021ccee9-88e3-454c-969a-0858d50fb555"),
                            Director = "Peter Jackson",
                            Genre = "Heroic-Fantasy",
                            MainActor = "Elijah Wood",
                            ReleaseYear = (short)2001,
                            Title = "LOTR - La communauté de l'anneau"
                        },
                        new
                        {
                            MovieId = new Guid("7fed4c53-4eda-4a10-9ac8-c6d505d26693"),
                            Director = "Peter Jackson",
                            Genre = "Heroic-Fantasy",
                            MainActor = "Elijah Wood",
                            ReleaseYear = (short)2002,
                            Title = "LOTR - Les deux tours"
                        },
                        new
                        {
                            MovieId = new Guid("61f0263f-25ea-4bec-84cc-bfb80fae52b4"),
                            Director = "Peter Jackson",
                            Genre = "Heroic-Fantasy",
                            MainActor = "Elijah Wood",
                            ReleaseYear = (short)2003,
                            Title = "LOTR - Le retour du roi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
